// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEO9TQ34e-b7vBRIvXmMqYpld7pKftWhI',
    appId: '1:848752043112:web:a8bb31040bb85e4c3dc7dd',
    messagingSenderId: '848752043112',
    projectId: 'helloart-a4111',
    authDomain: 'helloart-a4111.firebaseapp.com',
    storageBucket: 'helloart-a4111.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5xQNafGm_C95Kvzmvq1_E0AVEwVcy9g0',
    appId: '1:848752043112:android:9435d0296cea38f43dc7dd',
    messagingSenderId: '848752043112',
    projectId: 'helloart-a4111',
    storageBucket: 'helloart-a4111.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEO9TQ34e-b7vBRIvXmMqYpld7pKftWhI',
    appId: '1:848752043112:web:8493b71cd131f5713dc7dd',
    messagingSenderId: '848752043112',
    projectId: 'helloart-a4111',
    authDomain: 'helloart-a4111.firebaseapp.com',
    storageBucket: 'helloart-a4111.firebasestorage.app',
  );
}
